### ISSUE TITLE
Swork could be a great framework for Cloudflare Workers

### ISSUE THREAD

**Issue by creatorrr** [justin-lee-collins/swork#8]
Great work on swork, @justin-lee-collins ! I just stumbled upon this lib on npm and started using it in some of my projects. Not sure if you have looked into them, but [cloudflare](https://cloudflare.com) has recently launched a FaaS similar to Google Cloud Functions / AWS Lambda called [Cloudflare Workers](https://workers.cloudflare.com). The API is based on the ServiceWorker spec and swork seems like a natural fit. Is this something you have already thought about or would like to consider going forward?

**Comment by justin-lee-collins** [comment]
Thank you @creatorrr . What an incredible suggestion on using swork with Cloudflare workers. After seeing your comment and doing some digging, I now have a sample site being served by a Cloudflare worker built by swork.

[Cloudflare worker](https://rough-lab-1d8a.swork.workers.dev/)

I had to make one change to accommodate that Cloudflare workers do not have access to self.location and pushed that version up to npm (1.4.3).

Thanks again for suggesting that I look into this. It will be a part of my testing practice to ensure it is compatible with Cloudflare moving forward.

**Comment by creatorrr** [comment]
Wow, that's really good to hear! Thank you for pushing the update to npm as well. :)
Closing this issue for now.
